CONST MAIN_COLOR_HEX = "\#ae8e6f"
CONST SECONDARY_COLOR_HEX = "\#2e1e14"
CONST PURPLE_COLOR_HEX = "\#d19fe8"
CONST BLUE_COLOR_HEX = "\#86bbd8"
CONST GREEN_COLOR_HEX = "\#3a5a40"
CONST RED_COLOR_HEX = "\#bf211e"

VAR purple = PURPLE_COLOR_HEX
VAR blue = BLUE_COLOR_HEX
VAR green = GREEN_COLOR_HEX
VAR red = RED_COLOR_HEX